services:
  rathole-server:
    restart: unless-stopped
    container_name: rathole-server
    image: rapiz1/rathole
    command: ["--server", "/app/server.toml"]
    ports:
      - 2333:2333  # for rathole communication
      - 25566:25566 #minecraft 2
    volumes:
      - ./rathole-conf/server.toml:/app/server.toml

  rathole-client:
    restart: unless-stopped
    container_name: rathole-client
    image: rapiz1/rathole
    command: ["--client", "/app/client.toml"]
    network_mode: host
    volumes:
      - ./rathole-conf/client.toml:/app/client.toml
